// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/11/6 15:54:16
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/tom.shen/Desktop/mototec-project-management/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tom.shen/Desktop/mototec-project-management/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tom.shen/Desktop/mototec-project-management/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tom.shen/Desktop/mototec-project-management/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tom.shen/Desktop/mototec-project-management/plugins/**/*.{js,ts,mjs}","C:/Users/tom.shen/Desktop/mototec-project-management/composables/**/*.{js,ts,mjs}","C:/Users/tom.shen/Desktop/mototec-project-management/utils/**/*.{js,ts,mjs}","C:/Users/tom.shen/Desktop/mototec-project-management/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tom.shen/Desktop/mototec-project-management/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tom.shen/Desktop/mototec-project-management/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/tom.shen/Desktop/mototec-project-management/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;